alias pdf="microsoft-edge"
alias clip="xclip -selection clipboard && killall xclip"
alias cpwd="pwd | clip"
alias apv="source venv/bin/activate"
alias ape="source env/bin/activate"
alias cpv="python3 -m venv ./venv"
alias cpe="python3 -m venv ./env"
alias nvrun="__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia"
alias curdate="date +'%d-%m-%y'"
alias nh="nautilus . & disown > /dev/null 2> /dev/null"
alias commit="git add . && git commit -m"
alias deploy="git checkout deploy && git merge master && git push && git checkout master && clear && git branch -vv"
alias uni="cd ~/Dropbox/university/second-year"
alias compile="g++ -Wall"
alias scale="gsettings set org.gnome.desktop.interface text-scaling-factor"
